<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYG3yz2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYG3yz2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYG3yz2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYG3yz2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYG3yz2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'YG3yz2x',
    'container.build_id' => 'dd766272',
    'container.build_time' => 1582825636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYG3yz2x');
